export const sampleInvestorsData = [
  {
    firstName: "John",
    lastName: "Doe",
    type: "investor",
    industry: ["technology", "finance"],
    fundingStage: ["seed", "series-a"],
    preferredLocation: ["north-america"],
    jobTitle: "Investment Partner",
    mobileNumber: "+1234567890",
    linkedinUrl: "https://www.linkedin.com/in/johndoe",
    bio: "Experienced investor with focus on tech startups",
    createdAt: new Date().toISOString(),
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    type: "founder",
    industry: ["healthcare"],
    fundingStage: ["pre-seed"],
    preferredLocation: ["europe"],
    jobTitle: "CEO",
    mobileNumber: "+441234567890",
    linkedinUrl: "https://www.linkedin.com/in/janesmith",
    bio: "Healthcare entrepreneur building innovative solutions",
    createdAt: new Date().toISOString(),
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    type: "both",
    industry: ["technology", "consumer"],
    fundingStage: ["series-a", "series-b"],
    preferredLocation: ["north-america", "asia"],
    jobTitle: "Venture Partner",
    mobileNumber: "+813456789012",
    linkedinUrl: "https://www.linkedin.com/in/alexjohnson",
    bio: "Former founder now investing in early-stage startups",
    createdAt: new Date().toISOString(),
  },
];
